#include "htmlreportpresenter.h"

#include <QFile>
#include <QTextStream>
#include <qdir.h>

#include <presentation/dialogs/formatters/helphtmlformatter.h>
#include <business/validation/imagevalidationrulesfactory.h>

bool HtmlReportPresenter::createExtendedReportPage(const QString &folderPath,
                                                   const ComparableImage &firstOriginalImage,
                                                   const ComparableImage &secondOriginalImage,
                                                   QList<AutocomparisonReportEntry> reportEntries
                                                   )
{
    // Create the main folder
    QDir dir(folderPath);
    if (!dir.exists()) {
        dir.mkpath(".");
    }

    // Create the images subfolder
    QString imagesFolderPath = folderPath + "/images";
    QDir imagesDir(imagesFolderPath);
    if (!imagesDir.exists()) {
        imagesDir.mkpath(".");
    }

    auto provider = ImageValidationRulesFactory::createImageExtensionsInfoProvider();

    QImage firstOrigImage = firstOriginalImage.getImage();
    QImage secondOrigImage = secondOriginalImage.getImage();

    QString firtsOrigImageName = firstOriginalImage.getBaseName() +
                                 provider->getDeafaultSaveExtension(true);

    QString secondOrigImageName = secondOriginalImage.getBaseName() +
                                  provider->getDeafaultSaveExtension(true);;

    // Save the two main images
    firstOrigImage.save(imagesFolderPath + "/" + firtsOrigImageName);
    secondOrigImage.save(imagesFolderPath + "/" + secondOrigImageName);

    // Create the HTML report file
    QFile reportFile(folderPath + "/report.html");
    if (!reportFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false; // Exit if file couldn't be opened
    }

    QTextStream out(&reportFile);

    // Start writing the HTML content
    out << R"(<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Image Comparison Report</title>
        <style>
            .table1 td, .table1 th {
                text-align: center;
            }
            .table2 th {
                text-align: center;
            }
            .table2 td {
                text-align: left;
            }

            body { font-family: Arial, sans-serif; background-color: #f4f4f9; color: #333; margin: 0; padding: 20px; }
            h1 { font-size: 36px; color: #2c3e50; text-align: center; }
            h2 { font-size: 24px; color: #34495e; text-align: center; }
            table { margin: 20px auto; border-collapse: collapse; width: 80%; }
            th, td { border: 1px solid #ddd; padding: 10px; }
            th { background-color: #f4f4f9; font-weight: bold; }
            img { max-width: 300px; max-height: 200px; }
            hr { margin: 40px 0; border: none; border-top: 2px solid #ddd; }
            .additional-section { margin-top: 20px; }
        </style>
    </head>
    <body>
    )";

    // Add the main header
    out << R"(
    <div class="table1">
    <center>
    <h1>Image comparison report</h1>
    <h2>An analysis of )" << firtsOrigImageName << R"( and )"
            << secondOrigImageName << R"(</h2>
    <p>This report was generated by the TwinPix application. It provides a comparison of the two images, highlighting their differences and similarities.</p>
    <hr></center>
    )";

    // Add the comparison table
    out << R"(
    <table>
        <tr>
            <th>)" << firtsOrigImageName << R"(</th>
            <th>)" << secondOrigImageName << R"(</th>
        </tr>
        <tr>
     <td>
    <a href="images/)" << firtsOrigImageName
            << R"("><img src="images/)"
            << firtsOrigImageName << R"(" alt=")"
            << firtsOrigImageName << R"("></a></td><td><a href="images/)"
            << secondOrigImageName << R"("><img src="images/)"
            << secondOrigImageName << R"(" alt=")"
            << secondOrigImageName
            << R"("></a></td>
        </tr>
    </table>
    <hr>
    )";

    for (int i = 0; i < reportEntries.size(); i++) {
        const auto &reportEntry =reportEntries[i];
        auto textReport = reportEntry.getTextReport();
        auto imageReport = reportEntry.getImagereport();
        auto processorInfo = reportEntry.getImageProcessorInfo();
        if (!processorInfo) {
            continue;
        }
        if (imageReport) {
            out << R"(
            <div class="additional-section"><center><p><h2>)" << processorInfo.value().fullName << R"(</h2></p>)";
            QString additionalImagePath = imagesFolderPath +
                                          QDir::separator() +
                                          processorInfo.value().name + ".png";

            imageReport->save(additionalImagePath);
            out << R"(<a href="images/)"
                << processorInfo.value().name + ".png"
                << R"("><img src="images/)"
                << processorInfo.value().name + ".png"
                << R"(" alt=")"
                << processorInfo.value().name
                << R"("></a></center><br/>)";
        }
        else if (textReport){
            out << R"(<div class="additional-section"><p>)" << textReport.value() << R"(</p>)";
        } else {
            out << R"(<div class="additional-section"><p>)"
                << R"(<b><font color=\"red\">Error! The comparator does not provide a comparison result!</font></b>)"
                << R"(</p>)";
        }
        out << "</div></dev><br/><br/>";
    }

    out << R"(<br/><h1>Reference information on algorithms</h1>)";
    out << "<br/>Do not skip this section when reading the report, as it explains how these algorithms work "
           "and provides the default parameter values for the algorithms. This is important because running"
           " the algorithms in auto-analysis mode does not allow changing these parameters through "
           "dialog windows, and the algorithm uses default values.<br>";
    out << R"(<div class="table2">)";

    for (int i = 0; i < reportEntries.size(); i++) {
        const auto &reportEntry =reportEntries[i];
        auto processorInfo = reportEntry.getImageProcessorInfo();
        if (!processorInfo) {
            continue;
        }
        ImageProcessorInfo& info = processorInfo.value();

        out << R"(<div class="additional-section"><p><h2>)"
            << processorInfo.value().fullName
            << R"(</h2></p>)";

        out <<R"(<p style="text-align: left;">)";
        out << HelpHtmlFormatter::formatImageProcessorInfo(info);
        out <<R"(</p><br/>)";
     }
     out << R"(</div>)";

    out << R"(</body></html>)";

    return true;
}

bool HtmlReportPresenter::createSimpleReportPage(const QString &filePath,
                                                 const QString &firstOriginalImageName,
                                                 const QString &secondOriginalImageName,
                                                 const QString &reportText
                                                )
{
    // Create the HTML report file
    QFile reportFile(filePath);
    if (!reportFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false; // Exit if file couldn't be opened
    }

    QTextStream out(&reportFile);

    // Start writing the HTML content
    out << R"(<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Comparison Report</title>
    <style>
        body { font-family: Arial, sans-serif; text-align: center; background-color: #f4f4f9; color: #333; margin: 0; padding: 20px; }
        h1 { font-size: 36px; color: #2c3e50; }
        h2 { font-size: 24px; color: #34495e; }
        table { margin: 20px auto; border-collapse: collapse; width: 80%; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: center; }
        th { background-color: #f4f4f9; font-weight: bold; }
        img { max-width: 300px; max-height: 200px; }
        hr { margin: 40px 0; border: none; border-top: 2px solid #ddd; }
        .additional-section { margin-top: 20px; }
    </style>
</head>
<body>
)";
// Add the main header
    out << R"(
<h1>Image comparison report</h1>
<h2>An analysis of )" << QFileInfo(firstOriginalImageName).fileName() << R"( and )"
        << QFileInfo(secondOriginalImageName).fileName() << R"(</h2>
<p>This report was generated by the TwinPix application.</p>
<hr>
)";
/*
    out << R"(
            <div class="additional-section">
                <p><h2>)" << comparatorFullName << R"(</h2></p>
            )";
*/
    if (!reportText.isEmpty()){
        out << R"(
            <div class="additional-section">
                <p>)" << reportText << R"(</p>
            )";
    } else {
        out << R"(
            <div class="additional-section">
                <p>)" << "<b><font color=\"red\">Error! The comparator does not provide a comparison result!</font></b>" << R"(</p>
            )";
    }
    out << "</div>";

    // Close the HTML tags
    out << R"(
</body>
</html>
)";
    return true;
}
