name: Build and Package Qt Application

on:
  push:
    branches:
      - ga-build
  pull_request:
    branches:
      - ga-build
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          export SHELL=/bin/bash
          export PATH=${{ vars.QT_BIN_DIR_PATH }}:$PATH
          echo "PATH is set to: $PATH"
          which qmake

      - name: Build project
        run: |
          mkdir build
          cd build
          ${{ vars.QT_BIN_DIR_PATH }}/qmake ../TwinPix.pro
          make -j8

      - name: Deploy project
        run: |
          ${{ vars.QT_BIN_DIR_PATH }}/macdeployqt TwinPix.app
          tar -czvf TwinPix-macOS-arm64.tar.gz ./TwinPix.app
