name: Build and Package Qt Application

on:
  push:
    branches:
      - ga-build
  pull_request:
    branches:
      - ga-build
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          export SHELL=/bin/bash
          
      #- name: Install gtar
        #run: brew install gnu-tar
        
      - name: Build project
        run: |
          mkdir build
          cd build
          qmake ../TwinPix.pro
          make -j8

      - name: Deploy project
        run: |
          qmake ../TwinPix.pro
          make -j8

      - name: Package application into tar.gz
        run: |
          cd Qt_6_9_0_for_macOS-Release
          tar -czvf TwinPix-macOS-arm64.tar.gz TwinPix.app
