name: Build and Package Qt Application

on:
  push:
    branches:
      - ga-build
  pull_request:
    branches:
      - ga-build
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          export SHELL=/bin/bash
          export PATH=${{ vars.QT_BIN_DIR_PATH }}:$PATH
          echo "PATH is set to: $PATH"
          which qmake

      - name: Build project
        run: |
          mkdir -p ${{ vars.BUILD_DIR }}
          cd ${{ vars.BUILD_DIR }}
          ${{ vars.QT_BIN_DIR_PATH }}/qmake ../TwinPix.pro
          make -j8

      - name: Deploy project
        run: |
          cd ${{ vars.BUILD_DIR }}
          ${{ vars.QT_BIN_DIR_PATH }}/macdeployqt ${{ vars.BUILD_DIR }}/TwinPix.app
          mkdir TwinPix-dmg
          cp -R ${{ vars.BUILD_DIR }}/TwinPix.app TwinPix-dmg
          cp ${{ vars.BUILD_DIR }}/../ReadMe.txt TwinPix-dmg/
          ln -s /Applications TwinPix-dmg/Applications
          hdiutil create -volname "TwinPix (beta)" -srcfolder TwinPix-dmg -ov -format UDZO TwinPix-macOS-arm64.dmg

      - name: Upload .dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: TwinPix-DMG
          path: ${{ vars.BUILD_DIR }}/TwinPix-macOS-arm64.dmg
