name: Build and Package Qt Application

on:
  push:
    branches:
      - ga-build
  pull_request:
    branches:
      - ga-build

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build project
        run: |
          export PATH=/opt/homebrew/opt/ncurses/bin:$PATH
          export DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH
          mkdir build
          cd build
          qmake ../ImageDiff.pro
          make

      - name: Package application into tar.gz
        run: |
          cd build
          tar -czvf ImageDiff.tar.gz ImageDiff.app
