name: Build and Package Qt Application

on:
  workflow_dispatch:
  #push:
    #branches:
      #- develop
  #pull_request:
    #branches:
      #- develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          export SHELL=/bin/bash
      
      - name: Build project
        run: |
          mkdir build
          cd build
          qmake ../ImageDiff.pro
          make -j8

      - name: Package application into tar.gz
        run: |
          cd build
          tar -czvf ImageDiff-macOS-arm64.tar.gz ImageDiff.app
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-app
          path: build/ImageDiff-macOS-arm64.tar.gz
